services:
  # Ollama service for LLM
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    profiles:
      - cpu
      - default
      - gpu

  # CPU version
  app-cpu:
    build:
      context: ./backend
      dockerfile: Dockerfile.cpu
    ports:
      - "9091:9091"
    env_file:
      - ./backend/.env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434/v1
    depends_on:
      - ollama
    profiles:
      - cpu
      - default

  # GPU version
  app-gpu:
    build:
      context: ./backend
      dockerfile: Dockerfile.gpu
    ports:
      - "9091:9091"
    env_file:
      - ./backend/.env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434/v1
    depends_on:
      - ollama
    runtime: nvidia
    profiles:
      - gpu

  # Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    profiles:
      - cpu
      - default
      - gpu

volumes:
  ollama_data: